### ISSUE TITLE
wide_dim

### ISSUE THREAD

**Issue by yufengwhy** [Lapis-Hong/Wide-ResDnn#1]
In your code, '[wide_dim += hash_bucket_size](https://github.com/Lapis-Hong/Wide-ResDnn/blob/master/wide_resdnn/build_estimator.py#L52)'.

If all 39 features are used for wide part, then the number of cross feature should be very large, maybe 1000**39. So the above code should be 'wide_dim *= hash_bucket_size'

In the tf tutorial of wide & deep, only some features are selected for wide part. I wonder which to choose in criteo dataset? thx~

**Comment by Lapis-Hong** [comment]
actually, all features can used for wide part, but you could chose most import features as you like, I do not understand what is the problem of  'wide_dim += hash_bucket_size', not all features for cross feature, and cross features usually consist of 2 or 3 features, will not be 1000**39 dims. Hope it help you.

**Comment by yufengwhy** [comment]
which part in your code tells the chosen 2 or 3 features?

**Comment by Lapis-Hong** [comment]
you could refer to https://github.com/Lapis-Hong/wide_deep, all features conf are listed in conf/*.yaml, the Wide-ResDnn repo is still unfinished.
